# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
branches:
  only:
    - master
matrix:
  fast_finish: true
script:
  - yarn test
