# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
branches:
  only:
    - master
matrix:
  fast_finish: true
before_install:
  - openssl aes-256-cbc -K $encrypted_b148fb5d3428_key -iv $encrypted_b148fb5d3428_iv -in test/account.json.enc -out test/account.json -d
script:
  - yarn test:ci
